http:
  port: "80"
env: "local"
postgres:
  host: "localhost"
  port: "5432"
  username: "postgres"
  dbname: "spgl_tutor"
  sslmode: "disable"
smtp:
  host: "smtp.gmail.com"
  port: "587"
templatesPath: "./templates"
