http:
  port: "443"
  host: "spanglishtutor.ru"
env: "local"
postgres:
  port: "5436"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"
smtp:
  host: "smtp.gmail.com"
  port: "587"
templatesPath: "./templates"
