http:
  port: "8080"
env: "local"
postgres:
  host: "localhost"
  port: "1234"
  username: "username"
  dbname: "dbname"
  sslmode: "disable"
smtp:
  host: "smtp.gmail.com"
  port: "587"
templatesPath: "./templates"
